### ISSUE TITLE
Activities are not filtered 

### ISSUE THREAD

**Issue by javiergalipienso** [owlysk/CodeTimer#3]
When you select client, the projects are filtered by the selected client, but once the project is selected, the application shows all the activities of the company that you can see, it does not filter them by the previous fields.

**Comment by owlysk** [comment]
Hi,
this is not implemented for now. I will add this feature in next version.

**Comment by owlysk** [comment]
Hi again,
I implemented requested feature, check out new release -  [v1.0.6](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.6)

**Comment by javiergalipienso** [comment]
Sorry, 
I tried the new version 1.0.6 and it still does not filter the project activities. 
As you can see in the following picture, I select client and project and I get a list with all Kimai activities where it is impossible to know which one is related to this project.
Best regards.
![imagen](https://github.com/owlysk/CodeTimer/assets/121504729/24a3aa54-53c3-4756-a528-01dbc50c7aab)

**Comment by owlysk** [comment]
Hi, unfortunately I forgot to implement it in new timesheets. Please check out new release [v1.0.7](https://github.com/owlysk/CodeTimer/releases/tag/v1.0.7)
